# Generated by Django 6.0.1 on 2026-01-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('coding', 'Coding'), ('learning', 'Learning'), ('debugging', 'Debugging')], max_length=20)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user_uid', 'date', 'activity_type')},
            },
        ),
    ]
