# Generated by Django 6.0.1 on 2026-01-19 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('github_username', models.CharField(max_length=255)),
                ('github_token', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('auto_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 1, 19, 14, 4, 0, 688814, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2026, 1, 19, 14, 4, 0, 688826, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 14, 4, 0, 688193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user_uid',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user_uid', '-date'], name='activities__user_ui_866d48_idx'),
        ),
    ]
